const $=id=>document.getElementById(id);
let state={timeZone:'America/New_York',orders:[]}, exampleReady=false;
const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
function feedback(text,error=false){$('feedback').textContent=text;$('feedback').className=error?'error':'';}
function sample(){const parts=Object.fromEntries(new Intl.DateTimeFormat('en-US',{timeZone:state.timeZone,year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date()).map(p=>[p.type,p.value]));const d=new Date(`${parts.year}-${parts.month}-${parts.day}T00:00:00Z`);d.setUTCDate(d.getUTCDate()+1);const pickupDate=d.toISOString().slice(0,10);d.setUTCDate(d.getUTCDate()+1);$('payload').value=JSON.stringify({shipperOrderId:'AXL-'+Date.now(),pickupDate,deliveryDate:d.toISOString().slice(0,10),price:900,stops:[{stopNumber:1,city:'Milford',state:'MA',postalCode:'01757'},{stopNumber:2,city:'Shippensburg',state:'PA',postalCode:'17257'}],vehicles:[{year:'2010',make:'Toyota',model:'Corolla'}],transportationReleaseNotes:'Confirmar disponibilidad antes de recoger.'},null,2);}
async function api(path,body){const response=await fetch(path,body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await response.json();if(!response.ok)throw new Error(data.error||'Error al procesar');return data;}
function route(p){return(Array.isArray(p.stops)?p.stops:[]).map(x=>x&&`${x.city||'?'} (${x.state||'?'})`).join(' → ');}
function card(o,load=false){const a=el('article',undefined,'card');a.append(el('small',o.id));const status=load?'Disponible':o.result?.status||'Esperando resultado';a.append(el('div',status,'tag '+(status==='Accepted'||load?'good':status==='Cancelled'?'bad':'')));if(o.carrier)a.append(el('span','Assigned','tag good'));a.append(el('h3',route(o.payload)||'Solicitud con datos incompletos'));a.append(el('p',`${o.payload.pickupDate||'?'} → ${o.payload.deliveryDate||'?'} · $${o.payload.price??'?'} USD`));if(Array.isArray(o.payload.vehicles))a.append(el('p',o.payload.vehicles.map(v=>v?`${v.year??''} ${v.make??''} ${v.model??''}`:'').join(', ')));if(o.result)a.append(el('p',o.result.notes));else a.append(el('p','Decisión local: '+o.decision.status+'. Esperando el resultado desde la cola.'));if(o.carrier)a.append(el('p','Transportista: '+o.carrier));if(o.pending)a.append(el('small',`${o.pending} evento(s) pendiente(s) de confirmación.`));if(load){if(o.payload.transportationReleaseNotes)a.append(el('p',o.payload.transportationReleaseNotes));const b=el('button','Tomar carga →','primary');b.onclick=async()=>{b.disabled=true;try{await api('/api/orders/'+encodeURIComponent(o.id)+'/assign',{carrier:$('carrier-name').value});feedback('Carga asignada. Ya aparece en el historial.');await refresh();}catch(e){feedback(e.message,true);}finally{b.disabled=false;}};a.append(b);}const d=el('details');d.append(el('summary','Ver payload'),el('pre',JSON.stringify(load?o.payload:o.result||o.decision,null,2)));a.append(d);return a;}
function render(){const orders=state.orders;const available=orders.filter(o=>o.ready&&!o.carrier);$('total').textContent=orders.length;$('available').textContent=available.length;$('assigned').textContent=orders.filter(o=>o.carrier).length;$('pending').textContent=state.counts.pending;$('connection').textContent=(state.broker.ready?'● ':'○ ')+state.broker.message;$('zone').textContent=state.timeZone;for(const [id,list,load]of [['orders',orders,false],['loads',available,true]]){const target=$(id);target.replaceChildren(...(list.length?list.map(o=>card(o,load)):[el('p',load?'No hay cargas disponibles recibidas desde Solace.':'Todavía no has enviado solicitudes.','empty')]));}history();}
function history(){const filter=$('filter').value.toLowerCase();$('timeline').replaceChildren(...state.orders.filter(o=>o.id.toLowerCase().includes(filter)).map(o=>{const a=el('article',undefined,'history-item');a.append(el('h3',o.id));const list=el('ol');for(const event of o.timeline){const li=el('li');li.append(el('time',new Date(event.at).toLocaleString()),el('span',event.label));list.append(li);}a.append(list);return a;}));}
async function refresh(){try{state=await api('/api/state');render();if(!exampleReady){sample();exampleReady=true;}}catch{$('connection').textContent='Sin conexión con la aplicación local';}}
$('order-form').onsubmit=async e=>{e.preventDefault();const b=e.submitter;b.disabled=true;try{let payload;try{payload=JSON.parse($('payload').value);}catch{throw new Error('El JSON tiene un error de formato.');}const r=await api('/api/orders',payload);feedback(r.duplicate?'Solicitud ya registrada; no se duplicaron eventos.':'Solicitud guardada. Decisión local: '+r.order.decision.status+'.');await refresh();}catch(e){feedback(e.message,true);}finally{b.disabled=false;}};
$('example').onclick=sample;$('filter').oninput=history;
for(const b of document.querySelectorAll('[data-tab]'))b.onclick=()=>{for(const p of document.querySelectorAll('.panel'))p.hidden=p.id!==b.dataset.tab;for(const n of document.querySelectorAll('[data-tab]'))n.classList.toggle('selected',n===b);};
refresh();setInterval(refresh,2000);
